services:
  dev:
    build:
      context: ./
      dockerfile: ./docker/dockerfile.devbox
    volumes:
      - .:/tactifai:cached
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]